name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      # - name: Create pipenv-environment
      #   uses: dschep/install-pipenv-action@v1
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install --dev --pre
      - name: Run Unit Tests
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run coverage run -m unittest discover
      - name: Create Coverage Report
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run coverage xml
      # - name: Install Dependencies
      #   run: pipenv install --dev --pre
      # - name: Run Tests and Generate Coverate Report
      #   run: |
      #     pipenv run coverage run -m unittest discover
      #     pipenv run coverage xml
      - name: Uplad coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
          flags: unittests
