name: Unittests and Code Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{maxtrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Create pipenv-environment
        uses: dschep/install-pipenv-action@v1
      - name: Install Dependencies
        run: pipenv install --dev
      - name: Run Tests and Generate Coverate Report
      - run: |
          coverage run -m unittest discover
          coverage xml
      - name: Uplad coverage to Codecov
        uses: codecov/codecov-action
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
          fags: unittests
